[Fix] : 변경 Blue-Green Production 설정

diff --git a/jenkins/cd.jenkinsfile b/jenkins/cd.jenkinsfile
--- a/jenkins/cd.jenkinsfile
+++ b/jenkins/cd.jenkinsfile
@@ -2,124 +2,7 @@ pipeline {
     agent any
 
     stages {
-        stage ('[Test]') {
-            parallel {
-                stage ('BE Test') {
-                    steps {
-                        echo 'BE - Test start'
-                        dir ('backend/core-service'){
-                            sh'''
-                                chmod +x gradlew
-                                ./gradlew test
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'BE - Success Test'
-                        }
-                        failure {
-                            error 'BE - Fail Test'
-                        }
-                    }
-                }
-                stage ('FE Test') {
-                    steps {
-                        echo 'FE - Test start'
-                        dir ('frontend'){
-                            sh'''
-                                yarn cache clean
-                                yarn install
-                                yarn test
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'BE - Success Test'
-                        }
-                        failure {
-                            error 'BE - Fail Test'
-                        }
-                    }
-                }
-                stage ('SDK Test') {
-                    steps {
-                        echo 'JS SDK - Test start'
-                        dir ('sdk/js/js-sdk'){
-                            sh'''
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'JS SDK - Success Test'
-                        }
-                        failure {
-                            error 'JS SDK - Fail Test'
-                        }
-                    }
-                }
-            }
-        }
-        stage ('[SonarQube Reporting]') {
-            parallel {
-                stage ('BE Sonar') {
-                    steps {
-                        echo 'BE - Sonar start'
-                        dir ('backend/core-service'){
-                            sh'''
-                                chmod +x gradlew
-                                ./gradlew sonar
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'BE - Success SonarQube Reporting'
-                        }
-                        failure {
-                            error 'BE - Fail SonarQube Reporting'
-                        }
-                    }
-                }
-                stage ('FE Sonar') {
-                    steps {
-                        echo 'FE - SonarScanner start'
-                        dir ('frontend'){
-                            sh'''
-                                /opt/sonar-scanner/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -Dproject.settings=./sonar-scanner.properties
-                            '''
-                        }
-                    }
-                    post {
-                        success {
-                            echo 'BE - Success SonarQube Reporting'
-                        }
-                        failure {
-                            error 'BE - Fail SonarQube Reporting'
-                        }
-                    }
-                }
-                stage ('SDK Sonar') {
-                    steps {
-                        echo 'JS SDK - Sonar start'
-                        dir ('sdk/js/js-sdk'){
-                            sh'''
-                            '''
-                        }
-                    }
-                    post {
-                        success {
-                            echo 'JS SDK - Success Test'
-                        }
-                        failure {
-                            error 'JS SDK - Fail Test'
-                        }
-                    }
-                }
-            }
-        }
+
         stage ('[Build]') {
             parallel {
                 stage ('BE Build') {
@@ -140,41 +23,6 @@ pipeline {
                             error 'BE - Fail Build'
                         }
                     }              
-                }
-                stage ('FE Build') {
-                    steps {
-                        echo 'FE - Build start'
-                        dir ('frontend'){
-                            sh'''
-                                yarn build
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'FE - Success Build'
-                        }
-                        failure{
-                            error 'FE - Fail Build'
-                        }
-                    }    
-                }
-                 stage ('SDK Build') {
-                    steps {
-                        echo 'JS SDK - Build start'
-                        dir ('sdk/js/js-sdk'){
-                            sh'''
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'JS SDK - Success Test'
-                        }
-                        failure {
-                            error 'JS SDK - Fail Test'
-                        }
-                    }
                 }
             }
         }
@@ -198,94 +46,47 @@ pipeline {
                         }
                     }
                 }
-                stage ('FE deploy') {
-                    steps {
-                        echo 'FE - Deploy to Nginx'
-                        dir ('frontend'){
-                            sh'''
-                                yarn build
-                                cp -r ./dist/. /var/www/html/.
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'BE - Success Deploy to Nginx'
-                        }
-                        failure {
-                            error 'BE - Fail Deploy to Nginx'
-                        }
-                    }
-                }
-                stage ('SDK deploy') {
-                    steps {
-                        echo 'JS SDK - Deploy'
-                        dir ('sdk/js/js-sdk'){
-                            sh'''
-                            '''
-                        }
-                    }
-                    post{
-                        success {
-                            echo 'JS SDK - Success Deploy'
-                        }
-                        failure {
-                            error 'JS SDK - Fail Deploy'
-                        }
-                    }
-                }
+
             }
         }
         stage ('Service Start') {
             steps {
-                echo 'Service Start'
-                sh'''
-                    EXIST_BLUE=$(docker-compose ps | grep "backend-blue" | grep Up || echo "NoActive")
-                    echo "EXIST_BLUE: $EXIST_BLUE"
+                 script {
+                    def status = sh(script: '''
+                        EXIST_BLUE=$(docker-compose ps | grep "backend-blue" | grep Up || echo "NoActive")
+                        echo "EXIST_BLUE: $EXIST_BLUE"
+                    ''', returnStdout: true).trim()
 
-                    if [ "$EXIST_BLUE" = "NoActive" ]; then
-                        BEFORE_COLOR="green"
-                        AFTER_COLOR="blue"
-                        BEFORE_PORT=8001
-                        AFTER_PORT=8000
-                    else
-                        BEFORE_COLOR="blue"
-                        AFTER_COLOR="green"
-                        BEFORE_PORT=8000
-                        AFTER_PORT=8001
-                    fi
+                    def BEFORE_COLOR = status.contains("NoActive") ? "green" : "blue"
+                    def AFTER_COLOR = status.contains("NoActive") ? "blue" : "green"
+                    def BEFORE_PORT = status.contains("NoActive") ? 8001 : 8000
+                    def AFTER_PORT = status.contains("NoActive") ? 8000 : 8001
 
-                    echo "===== Continue =====";
-                    sed -i 's/${BEFORE_PORT}/${AFTER_PORT}/' /var/jenkins_home/workspace/lightswitch-web-cd/prometheus.yml
-                    scp -i /ssh/private/.pem /var/jenkins_home/workspace/lightswitch-web-cd/prometheus.yml ubuntu@ip-172-26-5-31:/home/ubuntu/prometheus/prometheus.yml
-                    export COMPOSE_PROFILES=$AFTER_COLOR
-                    docker-compose up -d --build
+                    sh "scp -i /ssh/private/.pem /var/jenkins_home/workspace/lightswitch-web-cd/prometheus.yml ubuntu@ip-172-26-5-31:/home/ubuntu/prometheus/prometheus.yml"
+                    sh "export COMPOSE_PROFILES=$AFTER_COLOR && docker-compose up -d --build"
 
-                    # 2
-                    for cnt in {1..10}
-                    do
-                        echo "===== 서버 응답 확인중(${cnt}/10) =====";
-                        UP=$(curl -s http://lightswitch.kr:${AFTER_PORT}/api/actuator/health)
-                        if [ -z "${UP}" ]
-                            then
-                                sleep 10
-                                continue
-                            else
-                                break
-                        fi
-                    done
+                    int retryCount = 0
+                    while (retryCount++ < 5) {
+                        echo "===== Checking server response (${retryCount}/10) ====="
+                        def UP = sh(script: "curl -s http://lightswitch.kr:${AFTER_PORT}/api/actuator/health || echo 'NoActive'", returnStdout: true).trim()
+                        if (UP == "NoActive") {
+                            sleep(10)
+                        } else {
+                            break
+                        }
+                    }
 
-                    if [ $cnt -eq 10 ]
-                    then
-                        echo "===== 서버 실행 실패 ====="
-                        exit 1
-                    fi
+                    if (retryCount == 5) {
+                        error("Server startup failed")
+                    }
 
-                    docker exec -it nginx /bin/bash -c "sed -i 's/${BEFORE_PORT}/${AFTER_PORT}/' /etc/nginx/conf.d/app.conf && nginx -s reload"
+                    sh """
+                        docker exec nginx /bin/bash -c "cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak && sed 's/${BEFORE_COLOR}:${BEFORE_PORT}/${AFTER_COLOR}:${AFTER_PORT}/' /etc/nginx/conf.d/default.conf.bak > /etc/nginx/conf.d/default.conf && nginx -s reload"
 
-                    echo "$BEFORE_COLOR server down(port:${BEFORE_PORT})"
-                    docker-compose stop backend-${BEFORE_COLOR}
-                '''
+                        echo "${BEFORE_COLOR} server down(port:${BEFORE_PORT})"
+                        docker-compose stop backend-${BEFORE_COLOR}
+                    """
+                }
             }
             post{
                 success {
